### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by helenchg** [helenchg/LearnUnity#1]
- [ ] Spatial Mapping & Spatial Understanding
- [x] Place agent in the physical world
- [x] Navmesh + Spatial Mapping of the physical world
- [x] Agent navigation in the physical world using NavMeshAgent

**Comment by helenchg** [comment]
- [ ] Air tap to save new destination as waypoint.
- [ ] Use voice commands to make agent walks towards the waypoint.
